language: php

php:
  - 5.3
  
before_script:
  - wget -nc http://getcomposer.org/composer.phar
  - php composer.phar install

script: phpunit -c phpunit.xml

notifications:
  email:
    - info@endroid.nl
